#include "internal.h"

#include <algorithm>
#include <cmath>
#include <map>
#include <set>

namespace wuw {
namespace {
constexpr float kNeg=-1.0e30f;
double Add(double a,double b){if(std::isinf(a)&&a<0)return b;if(std::isinf(b)&&b<0)return a;if(a<b)std::swap(a,b);return a+std::log1p(std::exp(b-a));}
double Forward(const std::vector<float>&p,int frames,int vocab,const std::vector<int64_t>&tokens,int blank){std::vector<int64_t>s{blank};for(auto t:tokens){s.push_back(t);s.push_back(blank);}std::vector<double>prev(s.size(),-INFINITY),cur(s.size());prev[0]=p[blank];if(s.size()>1)prev[1]=p[tokens[0]];for(int f=1;f<frames;++f){std::fill(cur.begin(),cur.end(),-INFINITY);for(size_t i=0;i<s.size();++i){double v=prev[i];if(i)v=Add(v,prev[i-1]);if(i>1&&(i%2==1)&&s[i]!=s[i-2])v=Add(v,prev[i-2]);cur[i]=v+p[f*vocab+s[i]];}prev.swap(cur);}return s.size()==1?prev[0]:Add(prev[s.size()-2],prev.back());}
using Prefix=std::vector<int64_t>;using Pair=std::pair<double,double>;
std::vector<std::pair<Prefix,double>> Beam(const std::vector<float>&p,int frames,int vocab,int blank,int width,int prune){std::map<Prefix,Pair>beam;beam[{}]={0,-INFINITY};for(int f=0;f<frames;++f){std::vector<int>tokens;for(int i=0;i<vocab;++i)if(i!=blank)tokens.push_back(i);std::sort(tokens.begin(),tokens.end(),[&](int a,int b){float x=p[f*vocab+a],y=p[f*vocab+b];return x==y?a<b:x>y;});if(static_cast<int>(tokens.size())>prune)tokens.resize(prune);std::map<Prefix,Pair>next;for(const auto&entry:beam){const Prefix&prefix=entry.first;double pb=entry.second.first,pn=entry.second.second,total=Add(pb,pn);auto&same=next[prefix];if(same.first==0&&same.second==0)same={-INFINITY,-INFINITY};same.first=Add(same.first,total+p[f*vocab+blank]);for(int token:tokens){double q=p[f*vocab+token];if(!prefix.empty()&&prefix.back()==token){auto&keep=next[prefix];keep.second=Add(keep.second,pn+q);if(!std::isinf(pb)){Prefix ext=prefix;ext.push_back(token);auto&x=next[ext];if(x.first==0&&x.second==0)x={-INFINITY,-INFINITY};x.second=Add(x.second,pb+q);}}else{Prefix ext=prefix;ext.push_back(token);auto&x=next[ext];if(x.first==0&&x.second==0)x={-INFINITY,-INFINITY};x.second=Add(x.second,total+q);}}}std::vector<std::pair<Prefix,double>>rank;for(auto&x:next)rank.push_back({x.first,Add(x.second.first,x.second.second)});std::sort(rank.begin(),rank.end(),[](const auto&a,const auto&b){return a.second==b.second?a.first<b.first:a.second>b.second;});beam.clear();for(int i=0;i<std::min(width,static_cast<int>(rank.size()));++i)beam[rank[i].first]=next[rank[i].first];}std::vector<std::pair<Prefix,double>>out;for(auto&x:beam)out.push_back({x.first,Add(x.second.first,x.second.second)});std::sort(out.begin(),out.end(),[](const auto&a,const auto&b){return a.second==b.second?a.first<b.first:a.second>b.second;});return out;}
}

BoundedCtcScorer::BoundedCtcScorer(std::vector<int64_t>tokens,int blank,int horizon):token_count_(tokens.size()),blank_id_(blank),horizon_(horizon){states_.push_back(blank);for(auto t:tokens){states_.push_back(t);states_.push_back(blank);}Reset();}
void BoundedCtcScorer::Reset(){frame_=0;scores_.assign(static_cast<size_t>(horizon_)*states_.size(),kNeg);ends_.assign(scores_.size(),-1);starts_.assign(horizon_,-1);}
Trace BoundedCtcScorer::Step(const float*p,int vocab,int64_t frame){if(frame!=frame_)throw Error(WUW_SDK_STATUS_INTERNAL_ERROR,"non-contiguous CTC frame");const int states=static_cast<int>(states_.size()),slot=static_cast<int>(frame%horizon_);for(int s=0;s<states;++s){scores_[slot*states+s]=kNeg;ends_[slot*states+s]=-1;}starts_[slot]=-1;std::vector<float>next(scores_.size(),kNeg);std::vector<int64_t>next_end(ends_.size(),-1);for(int row=0;row<horizon_;++row){for(int s=1;s<states;++s){auto choose=[&](int predecessor,float*best,int64_t*end){float q=scores_[row*states+predecessor];int64_t e=ends_[row*states+predecessor];if(q>*best||(q==*best&&e<*end)){*best=q;*end=e;}};float best=scores_[row*states+s];int64_t end=ends_[row*states+s];choose(s-1,&best,&end);if(s>1&&(s%2==1)&&states_[s]!=states_[s-2])choose(s-2,&best,&end);if(best>kNeg/2){next[row*states+s]=best+p[states_[s]];next_end[row*states+s]=(s%2==1)?frame:end;}}}scores_.swap(next);ends_.swap(next_end);starts_[slot]=frame;scores_[slot*states+1]=p[states_[1]];ends_[slot*states+1]=frame;Trace out;out.score=kNeg/static_cast<float>(token_count_);for(int row=0;row<horizon_;++row){float score=scores_[row*states+states-2];int64_t end=ends_[row*states+states-2];float b=scores_[row*states+states-1];int64_t be=ends_[row*states+states-1];if(b>score||(b==score&&be<end)){score=b;end=be;}int64_t start=starts_[row];if(score>out.score||(score==out.score&&(start>out.start||(start==out.start&&end<out.end)))){out.score=score;out.start=start;out.end=end;}}out.score/=static_cast<float>(token_count_);++frame_;return out;}

float KeywordVsFillerConfidence(const std::vector<float>&p,int frames,int vocab,const std::vector<int64_t>&keyword,int blank,int beam_size,int token_prune){auto hypotheses=Beam(p,frames,vocab,blank,beam_size,token_prune);const Prefix*filler=nullptr;for(auto&h:hypotheses)if(h.first!=keyword){filler=&h.first;break;}if(!filler)throw Error(WUW_SDK_STATUS_INTERNAL_ERROR,"CTC beam did not retain a filler");double raw=(Forward(p,frames,vocab,keyword,blank)-Forward(p,frames,vocab,*filler,blank))/frames;return static_cast<float>(raw>=0?1/(1+std::exp(-raw)):std::exp(raw)/(1+std::exp(raw)));}
}  // namespace wuw
