#include "internal.h"

#include <algorithm>
#include <cmath>
#include <cstring>

namespace wuw {
namespace {
uint64_t Micros(std::chrono::steady_clock::duration d){return static_cast<uint64_t>(std::chrono::duration_cast<std::chrono::microseconds>(d).count());}
}
StreamImpl::StreamImpl(std::shared_ptr<EngineImpl> e):engine(std::move(e)),fbank_(engine->config.contract.sample_rate,engine->config.contract.feature_dim,engine->config.contract.frame_length,engine->config.contract.frame_shift){stats.struct_size=sizeof(stats);Reset();}
void StreamImpl::ClearSegmentState(){fbank_.Reset();pending_features_.clear();pending_frames_=0;offset_=engine->config.contract.initial_offset;chunks_run_=0;std::fill(att_cache_.begin(),att_cache_.end(),0);std::fill(cnn_cache_.begin(),cnn_cache_.end(),0);for(auto&s:scorers_)s->Reset();std::fill(previous_above_.begin(),previous_above_.end(),false);last_traces_.assign(engine->config.keywords.size(),Trace{});encoder_frame_=0;encoder_ring_.clear();ctc_ring_.clear();last_candidate_.reset();segment_samples_=0;}
void StreamImpl::Reset(){active_=false;events_.clear();last_detection_end_=std::numeric_limits<int64_t>::min()/2;std::memset(&stats,0,sizeof(stats));stats.struct_size=sizeof(stats);const auto&c=engine->config.contract;att_cache_.assign(static_cast<size_t>(c.num_layers)*c.num_heads*c.required_cache_size*c.head_dim,0);cnn_cache_.assign(static_cast<size_t>(c.num_layers)*c.cnn_channels*c.cnn_cache,0);scorers_.clear();for(const auto&k:engine->config.keywords)scorers_.push_back(std::make_unique<BoundedCtcScorer>(k.tokens,c.blank_id,engine->config.max_search_frames));previous_above_.resize(scorers_.size());ClearSegmentState();}
void StreamImpl::Begin(uint64_t id,int64_t first){if(active_)throw Error(WUW_SDK_STATUS_INVALID_STATE,"a segment is already active");ClearSegmentState();active_=true;segment_id_=id;segment_first_sample_=first;++stats.segments_started;}
void StreamImpl::Accept(const int16_t*samples,size_t count){if(!active_)throw Error(WUW_SDK_STATUS_INVALID_STATE,"begin_segment must be called first");if(count&&!samples)throw Error(WUW_SDK_STATUS_INVALID_ARGUMENT,"samples is null");auto started=std::chrono::steady_clock::now();fbank_.Accept(samples,count);segment_samples_+=count;stats.samples_accepted+=count;ProcessAvailable(false);uint64_t elapsed=Micros(std::chrono::steady_clock::now()-started);stats.processing_time_us+=elapsed;stats.max_accept_time_us=std::max(stats.max_accept_time_us,elapsed);}
void StreamImpl::ProcessAvailable(bool final){auto frames=fbank_.ReadFrames();for(auto&f:frames)pending_features_.insert(pending_features_.end(),f.begin(),f.end());pending_frames_+=static_cast<int>(frames.size());const auto&c=engine->config.contract;while(pending_frames_>=c.chunk_frames){RunChunk(c.chunk_frames);pending_features_.erase(pending_features_.begin(),pending_features_.begin()+static_cast<std::ptrdiff_t>(c.chunk_stride*c.feature_dim));pending_frames_-=c.chunk_stride;}if(final&&pending_frames_>=c.minimum_chunk_frames){RunChunk(pending_frames_);pending_features_.clear();pending_frames_=0;}}
void StreamImpl::RunChunk(int frames){const auto&c=engine->config.contract;std::vector<float>input(pending_features_.begin(),pending_features_.begin()+static_cast<std::ptrdiff_t>(frames*c.feature_dim));std::vector<uint8_t>mask(static_cast<size_t>(c.required_cache_size+16),1);int valid=std::min(c.required_cache_size,chunks_run_*16),invalid=c.required_cache_size-valid;std::fill(mask.begin(),mask.begin()+invalid,0);std::vector<float>next_att,next_cnn;Stage1Output out=engine->model->RunStage1(input,frames,offset_,att_cache_,cnn_cache_,mask,&next_att,&next_cnn);att_cache_.swap(next_att);cnn_cache_.swap(next_cnn);offset_+=out.frames;++chunks_run_;++stats.stage1_chunks;for(int i=0;i<out.frames;++i)ProcessEncoderFrame(out.encoder.data()+static_cast<size_t>(i)*c.encoder_dim,out.ctc.data()+static_cast<size_t>(i)*c.vocabulary_size,false);}
void StreamImpl::ProcessEncoderFrame(const float*encoder,const float*ctc,bool synthetic){const auto&c=engine->config.contract;if(synthetic){if(encoder_frame_>0){size_t winner=0;for(size_t i=1;i<last_traces_.size();++i)if(last_traces_[i].score>last_traces_[winner].score)winner=i;float second=-INFINITY;for(size_t i=0;i<last_traces_.size();++i)if(i!=winner)second=std::max(second,last_traces_[i].score);MaybeCandidate(winner,last_traces_[winner],last_traces_[winner].score,last_traces_[winner].score-second,true);}return;}
  std::vector<float>ev(encoder,encoder+c.encoder_dim),cv(ctc,ctc+c.vocabulary_size);encoder_ring_.push_back({encoder_frame_,std::move(ev)});ctc_ring_.push_back({encoder_frame_,std::move(cv)});while(!encoder_ring_.empty()&&encoder_ring_.front().first<encoder_frame_-engine->config.max_search_frames-8)encoder_ring_.pop_front();while(!ctc_ring_.empty()&&ctc_ring_.front().first<encoder_frame_-engine->config.max_search_frames-4)ctc_ring_.pop_front();
  size_t winner=0;for(size_t i=0;i<scorers_.size();++i){last_traces_[i]=scorers_[i]->Step(ctc,c.vocabulary_size,encoder_frame_);if(last_traces_[i].score>last_traces_[winner].score)winner=i;}float second=-INFINITY;for(size_t i=0;i<last_traces_.size();++i)if(i!=winner)second=std::max(second,last_traces_[i].score);MaybeCandidate(winner,last_traces_[winner],last_traces_[winner].score,last_traces_[winner].score-second,false);++encoder_frame_;
}
void StreamImpl::MaybeCandidate(size_t winner,const Trace&trace,float top,float margin,bool synthetic){(void)synthetic;std::vector<bool>now(previous_above_.size(),false);if(trace.start<0||trace.end<trace.start||trace.end>=encoder_frame_||top<engine->config.proposal_floor){previous_above_.swap(now);return;}const auto&c=engine->config.contract;std::vector<float>segment;for(const auto&row:ctc_ring_)if(row.first>=trace.start&&row.first<=trace.end)segment.insert(segment.end(),row.second.begin(),row.second.end());int frames=static_cast<int>(segment.size()/c.vocabulary_size);if(frames!=trace.end-trace.start+1){previous_above_.swap(now);return;}float stage1=KeywordVsFillerConfidence(segment,frames,c.vocabulary_size,engine->config.keywords[winner].tokens,c.blank_id,engine->config.competitor_beam,engine->config.token_prune);now[winner]=stage1>=engine->config.keywords[winner].threshold;bool rising=now[winner]&&!previous_above_[winner];previous_above_.swap(now);auto key=std::make_pair(winner,std::make_pair(trace.start,trace.end));if(!rising||last_candidate_==key)return;last_candidate_=key;++stats.stage1_candidates;
  int64_t crop_start=std::max<int64_t>(0,trace.start-engine->config.pre_margin),crop_end=trace.end+1+engine->config.post_margin;std::vector<float>crop;for(const auto&row:encoder_ring_)if(row.first>=crop_start&&row.first<crop_end)crop.insert(crop.end(),row.second.begin(),row.second.end());int crop_frames=static_cast<int>(crop.size()/c.encoder_dim);if(crop_frames<=0)return;++stats.stage2_runs;float probability=engine->model->RunStage2(crop,crop_frames,top,margin,static_cast<int>(winner),static_cast<int>(engine->config.keywords.size()));if(probability<engine->config.stage2_threshold)return;int64_t start_sample=segment_first_sample_+trace.start*c.encoder_frame_samples,end_sample=segment_first_sample_+(trace.end+1)*c.encoder_frame_samples;if(end_sample-last_detection_end_<engine->config.debounce_samples)return;if(events_.size()>=64)throw Error(WUW_SDK_STATUS_RESOURCE_EXHAUSTED,"event queue is full; read events more often");events_.push_back({segment_id_,start_sample,end_sample,segment_first_sample_+static_cast<int64_t>(segment_samples_),probability,winner});last_detection_end_=end_sample;++stats.detections;}
void StreamImpl::End(){if(!active_)throw Error(WUW_SDK_STATUS_INVALID_STATE,"no active segment");auto started=std::chrono::steady_clock::now();ProcessAvailable(true);ProcessEncoderFrame(nullptr,nullptr,true);active_=false;stats.processing_time_us+=Micros(std::chrono::steady_clock::now()-started);}
size_t StreamImpl::Read(WuwSdkEvent*out,size_t capacity){if(capacity&&!out)throw Error(WUW_SDK_STATUS_INVALID_ARGUMENT,"events is null");size_t n=std::min(capacity,events_.size());for(size_t i=0;i<n;++i){const auto&e=events_.front();WuwSdkEvent v{};v.struct_size=sizeof(v);v.segment_id=e.segment_id;v.start_sample_index=e.start_sample;v.end_sample_index=e.end_sample;v.detection_sample_index=e.detection_sample;v.confidence=e.confidence;CopyString(engine->config.keywords[e.keyword].id,v.keyword_id,sizeof(v.keyword_id));CopyString(engine->config.keywords[e.keyword].display,v.display_text,sizeof(v.display_text));out[i]=v;events_.pop_front();}return n;}
}  // namespace wuw
