#ifndef WUW_SDK_TOOL_COMMON_H_
#define WUW_SDK_TOOL_COMMON_H_
#include <algorithm>
#include <cstdint>
#include <fstream>
#include <stdexcept>
#include <string>
#include <vector>
#include "wuw_sdk/wuw.hpp"
namespace tool {
inline uint16_t U16(const unsigned char*p){return uint16_t(p[0])|(uint16_t(p[1])<<8);}inline uint32_t U32(const unsigned char*p){return uint32_t(p[0])|(uint32_t(p[1])<<8)|(uint32_t(p[2])<<16)|(uint32_t(p[3])<<24);}
class WavReader{public:explicit WavReader(const std::string&path):in_(path,std::ios::binary),path_(path){if(!in_)throw std::runtime_error("cannot open WAV: "+path);unsigned char head[12];in_.read(reinterpret_cast<char*>(head),12);if(in_.gcount()!=12||std::string(reinterpret_cast<char*>(head),4)!="RIFF"||std::string(reinterpret_cast<char*>(head+8),4)!="WAVE")throw std::runtime_error("not a RIFF/WAVE file: "+path);bool fmt=false;while(in_){unsigned char h[8];in_.read(reinterpret_cast<char*>(h),8);if(in_.gcount()!=8)break;uint32_t n=U32(h+4);std::string id(reinterpret_cast<char*>(h),4);if(id=="fmt "){std::vector<unsigned char>x(n);in_.read(reinterpret_cast<char*>(x.data()),n);if(n<16)throw std::runtime_error("invalid WAV fmt: "+path);format_=U16(x.data());channels_=U16(x.data()+2);rate_=U32(x.data()+4);bits_=U16(x.data()+14);fmt=true;if(n&1)in_.get();}else if(id=="data"){remaining_=n;break;}else in_.seekg(n+(n&1),std::ios::cur);}uint64_t frame_bytes=2*channels_;if(!fmt||!remaining_||format_!=1||channels_<1||rate_!=16000||bits_!=16||remaining_%frame_bytes)throw std::runtime_error("evaluation WAV must be PCM16 16000 Hz: "+path);total_samples_=remaining_/frame_bytes;}size_t Read(int16_t*out,size_t capacity){size_t n=std::min<uint64_t>(capacity,remaining_/(2*channels_));std::vector<unsigned char>raw(n*2*channels_);in_.read(reinterpret_cast<char*>(raw.data()),static_cast<std::streamsize>(raw.size()));if(static_cast<size_t>(in_.gcount())!=raw.size())throw std::runtime_error("truncated WAV: "+path_);for(size_t i=0;i<n;++i){int64_t sum=0;for(size_t c=0;c<channels_;++c)sum+=static_cast<int16_t>(U16(raw.data()+2*(i*channels_+c)));out[i]=static_cast<int16_t>(sum/channels_);}remaining_-=raw.size();return n;}uint64_t total_samples()const{return total_samples_;}private:std::ifstream in_;std::string path_;uint16_t format_=0,channels_=0,bits_=0;uint32_t rate_=0;uint64_t remaining_=0,total_samples_=0;};
inline std::vector<int16_t> ReadWav(const std::string&path){std::ifstream in(path,std::ios::binary);if(!in)throw std::runtime_error("cannot open WAV: "+path);unsigned char head[12];in.read(reinterpret_cast<char*>(head),12);if(in.gcount()!=12||std::string(reinterpret_cast<char*>(head),4)!="RIFF"||std::string(reinterpret_cast<char*>(head+8),4)!="WAVE")throw std::runtime_error("not a RIFF/WAVE file: "+path);uint16_t format=0,channels=0,bits=0;uint32_t rate=0;std::vector<char>data;while(in){unsigned char h[8];in.read(reinterpret_cast<char*>(h),8);if(in.gcount()!=8)break;uint32_t n=U32(h+4);std::string id(reinterpret_cast<char*>(h),4);std::vector<char>chunk(n);in.read(chunk.data(),n);if(static_cast<uint32_t>(in.gcount())!=n)throw std::runtime_error("truncated WAV: "+path);if(n&1)in.get();if(id=="fmt "&&n>=16){auto*p=reinterpret_cast<unsigned char*>(chunk.data());format=U16(p);channels=U16(p+2);rate=U32(p+4);bits=U16(p+14);}else if(id=="data")data=std::move(chunk);}if(format!=1||channels!=1||rate!=16000||bits!=16||data.size()%2)throw std::runtime_error("SDK requires mono PCM16 16000 Hz WAV: "+path);std::vector<int16_t>out(data.size()/2);for(size_t i=0;i<out.size();++i){auto*p=reinterpret_cast<const unsigned char*>(data.data()+2*i);out[i]=static_cast<int16_t>(U16(p));}return out;}
inline std::string JsonString(const std::string&line,const std::string&key){std::string needle="\""+key+"\"";size_t p=line.find(needle);if(p==std::string::npos)return{};p=line.find(':',p+needle.size());if(p==std::string::npos)return{};p=line.find('"',p+1);if(p==std::string::npos)return{};std::string out;for(++p;p<line.size();++p){char c=line[p];if(c=='"')return out;if(c=='\\'&&p+1<line.size()){char e=line[++p];if(e=='n')out+='\n';else if(e=='t')out+='\t';else out+=e;}else out+=c;}return{};}
inline std::string Escape(const std::string&s){std::string o;for(char c:s){if(c=='"'||c=='\\'){o+='\\';o+=c;}else if(c=='\n')o+="\\n";else o+=c;}return o;}
inline void Check(WuwSdkStatus s,const void*h=nullptr){if(s!=WUW_SDK_STATUS_OK)throw std::runtime_error(wuw_sdk_last_error_message(h));}
}
#endif
